#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:           docker_images
# Required-Start:     $syslog $remote_fs docker
# Required-Stop:      $syslog $remote_fs
# Should-Start:       
# Should-Stop:        
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  Create lightweight, portable, self-sufficient containers.
# Description:
#     Starts default system docker images
### END INIT INFO

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

sleep 10s
/usr/bin/jjs /opt/docker_images/docker_images.js -- $@
