#!/bin/sh

ID=`id -u`
if [ $ID -ne 0 ]
then
    echo "You must be root"
    exit 1
fi

. ./core.sh

# Mount media drive
if [ ! -d /mnt/media/docker-data/repo ]
then
    mkdir -p /mnt/media
    mount -L media /mnt/media
    
    if [ ! -d /mnt/media/docker-data/repo ]
    then
        echo "The media drive does not contain /mnt/media/docker-data/repo"
        exit 4
    fi
fi

# Install JAVA
if [ ! -d /opt/jdk ]
then
    FOLDER="`pwd`"
    cd /opt
    tar -xzf /mnt/media/docker-data/repo/jdk-8u25-linux-x64.tar.gz
    ln -s /opt/jdk1.8.0_25 /opt/jdk
    ln -s /opt/jdk/bin/jjs /usr/bin/jjs
    cd "$FOLDER"
fi

echo 'export JAVA_HOME=/opt/jdk' >>/etc/bash.bashrc
echo 'export PATH=$PATH:/opt/jdk/bin' >>/etc/bash.bashrc

# A http server needed for Docker additions
jjs httpd.js &

echo Installing system:
jjs make.js
killall jjs
